/**
 * useEngine — Manages the connection to the WOTANN Engine (KAIROS daemon).
 *
 * Responsibilities:
 * - Initializes the store with real data on mount
 * - Polls status every 5 seconds
 * - Polls agents and cost every 10 seconds
 * - Handles connection/disconnection gracefully
 *
 * Should be called once at the app root level.
 */

import { useEffect, useRef } from "react";
import { listen } from "@tauri-apps/api/event";
import {
  initializeFromEngine,
  refreshStatus,
  refreshAgents,
  refreshCost,
  loadPersistedSettings,
  checkAmbientSuggestions,
  pollDaemonNotifications,
} from "../store/engine";
import { useStore } from "../store";
import type { RuntimeStatus, AgentInfo, CostSnapshot } from "../types";

/** Status polling interval: 5 seconds */
const STATUS_INTERVAL_MS = 5_000;

/** Agents + cost polling interval: 10 seconds */
const SLOW_INTERVAL_MS = 10_000;

/** Ambient suggestions interval: 60 seconds */
const AMBIENT_INTERVAL_MS = 60_000;

export function useEngine(): void {
  const initializedRef = useRef(false);

  useEffect(() => {
    // Guard against double-initialization in React StrictMode
    if (initializedRef.current) return;
    initializedRef.current = true;

    // Load persisted settings first (theme, preferences, etc.)
    loadPersistedSettings();

    // Populate the store with real engine data
    initializeFromEngine();

    // Set up polling intervals (fallback when events don't fire)
    const statusInterval = setInterval(refreshStatus, STATUS_INTERVAL_MS);
    const agentsInterval = setInterval(refreshAgents, SLOW_INTERVAL_MS);
    const costInterval = setInterval(refreshCost, SLOW_INTERVAL_MS);
    const ambientInterval = setInterval(checkAmbientSuggestions, AMBIENT_INTERVAL_MS);

    // Poll daemon notifications alongside ambient checks.
    // Daemon notifications (CI failures, spec divergences, stalled tasks)
    // are generated by KAIROS but don't reach the in-app store without this.
    const daemonNotifInterval = setInterval(pollDaemonNotifications, AMBIENT_INTERVAL_MS);

    // ── Tauri Event Listeners (instant updates alongside polling fallback) ──
    // Events from the Rust backend give instant updates without waiting
    // for the next poll cycle. Polling remains as a fallback for resilience.
    const unlistenFns: (() => void)[] = [];

    // Status changes via event (instant) instead of polling (5s delay)
    listen<RuntimeStatus>("wotann:status-changed", (event) => {
      const status = event.payload;
      const userProvider = localStorage.getItem("wotann-selected-provider");
      const userModel = localStorage.getItem("wotann-selected-model");
      useStore.setState({
        engineConnected: status.connected,
        provider: userProvider || status.provider,
        model: userModel || status.model,
        totalTokens: status.totalTokens,
        contextPercent: status.contextPercent,
      });
    }).then((fn) => unlistenFns.push(fn)).catch(() => {});

    // Agent updates via event
    listen<readonly AgentInfo[]>("wotann:agents-updated", (event) => {
      useStore.setState({ agents: event.payload });
    }).then((fn) => unlistenFns.push(fn)).catch(() => {});

    // Cost updates via event
    listen<CostSnapshot>("wotann:cost-updated", (event) => {
      useStore.setState({ cost: event.payload });
    }).then((fn) => unlistenFns.push(fn)).catch(() => {});

    return () => {
      // Clean up event listeners
      for (const fn of unlistenFns) {
        fn();
      }
      clearInterval(statusInterval);
      clearInterval(agentsInterval);
      clearInterval(costInterval);
      clearInterval(ambientInterval);
      clearInterval(daemonNotifInterval);
      initializedRef.current = false;
    };
  }, []);
}
