// AUTO-GENERATED by src/design/token-emitters/ios.ts. DO NOT EDIT.
// Source: src/design/tokens.ts
// Regenerate: node scripts/generate-tokens.mjs
//
// Pairs with DesignSystem/Theme.swift — this file provides the raw generated
// token values; Theme.swift composes them into the live runtime API.

import SwiftUI
import Foundation

/// Generated WOTANN design tokens.
public enum WotannTokens {

    // MARK: - Palettes (5 canonical)

    public enum Dark {
        public static let background = Color(hex: 0x08080C)
        public static let surface = Color(hex: 0x131318)
        public static let text = Color(hex: 0xE6E6EB)
        public static let muted = Color(hex: 0x8B8B96)
        public static let border = Color(hex: 0x2A2A33)
        public static let accent = Color(hex: 0x06B6D4)
        public static let accentMuted = Color(hex: 0x0891B2)
        public static let info = Color(hex: 0x60A5FA)
        public static let success = Color(hex: 0x34D399)
        public static let warning = Color(hex: 0xFBBF24)
        public static let error = Color(hex: 0xF87171)
        public static let userMessage = Color(hex: 0x60A5FA)
        public static let assistantMessage = Color(hex: 0x34D399)
        public static let systemMessage = Color(hex: 0xFBBF24)
        public static let toolMessage = Color(hex: 0x06B6D4)
        public static let hudGreen = Color(hex: 0x34D399)
        public static let hudYellow = Color(hex: 0xFBBF24)
        public static let hudOrange = Color(hex: 0xF97316)
        public static let hudRed = Color(hex: 0xF87171)
    }

    public enum Light {
        public static let background = Color(hex: 0xFAFAFA)
        public static let surface = Color(hex: 0xF0F0F3)
        public static let text = Color(hex: 0x1E1E24)
        public static let muted = Color(hex: 0x6B6B75)
        public static let border = Color(hex: 0xD4D4DC)
        public static let accent = Color(hex: 0x0891B2)
        public static let accentMuted = Color(hex: 0x0E7490)
        public static let info = Color(hex: 0x2563EB)
        public static let success = Color(hex: 0x059669)
        public static let warning = Color(hex: 0xD97706)
        public static let error = Color(hex: 0xDC2626)
        public static let userMessage = Color(hex: 0x2563EB)
        public static let assistantMessage = Color(hex: 0x059669)
        public static let systemMessage = Color(hex: 0xD97706)
        public static let toolMessage = Color(hex: 0x0891B2)
        public static let hudGreen = Color(hex: 0x059669)
        public static let hudYellow = Color(hex: 0xD97706)
        public static let hudOrange = Color(hex: 0xEA580C)
        public static let hudRed = Color(hex: 0xDC2626)
    }

    public enum HighContrast {
        public static let background = Color(hex: 0x000000)
        public static let surface = Color(hex: 0x0A0A0A)
        public static let text = Color(hex: 0xFFFFFF)
        public static let muted = Color(hex: 0xCCCCCC)
        public static let border = Color(hex: 0xFFFFFF)
        public static let accent = Color(hex: 0x00FFFF)
        public static let accentMuted = Color(hex: 0x00CCCC)
        public static let info = Color(hex: 0x00FFFF)
        public static let success = Color(hex: 0x00FF00)
        public static let warning = Color(hex: 0xFFFF00)
        public static let error = Color(hex: 0xFF0000)
        public static let userMessage = Color(hex: 0x00FFFF)
        public static let assistantMessage = Color(hex: 0x00FF00)
        public static let systemMessage = Color(hex: 0xFFFF00)
        public static let toolMessage = Color(hex: 0xFFFFFF)
        public static let hudGreen = Color(hex: 0x00FF00)
        public static let hudYellow = Color(hex: 0xFFFF00)
        public static let hudOrange = Color(hex: 0xFF8000)
        public static let hudRed = Color(hex: 0xFF0000)
    }

    public enum Sepia {
        public static let background = Color(hex: 0x1A1410)
        public static let surface = Color(hex: 0x241B14)
        public static let text = Color(hex: 0xEBD5B3)
        public static let muted = Color(hex: 0x9C8972)
        public static let border = Color(hex: 0x3D2F1F)
        public static let accent = Color(hex: 0xD4A853)
        public static let accentMuted = Color(hex: 0xA88540)
        public static let info = Color(hex: 0xC8A876)
        public static let success = Color(hex: 0x8CB368)
        public static let warning = Color(hex: 0xE8A857)
        public static let error = Color(hex: 0xC87A5E)
        public static let userMessage = Color(hex: 0xC8A876)
        public static let assistantMessage = Color(hex: 0xD4A853)
        public static let systemMessage = Color(hex: 0xE8A857)
        public static let toolMessage = Color(hex: 0xB89468)
        public static let hudGreen = Color(hex: 0x8CB368)
        public static let hudYellow = Color(hex: 0xE8A857)
        public static let hudOrange = Color(hex: 0xD17D3D)
        public static let hudRed = Color(hex: 0xC87A5E)
    }

    public enum Monochrome {
        public static let background = Color(hex: 0x000000)
        public static let surface = Color(hex: 0x111111)
        public static let text = Color(hex: 0xE0E0E0)
        public static let muted = Color(hex: 0x808080)
        public static let border = Color(hex: 0x333333)
        public static let accent = Color(hex: 0xFFFFFF)
        public static let accentMuted = Color(hex: 0xCCCCCC)
        public static let info = Color(hex: 0xBDBDBD)
        public static let success = Color(hex: 0xD0D0D0)
        public static let warning = Color(hex: 0x999999)
        public static let error = Color(hex: 0x666666)
        public static let userMessage = Color(hex: 0xE0E0E0)
        public static let assistantMessage = Color(hex: 0xFFFFFF)
        public static let systemMessage = Color(hex: 0xAAAAAA)
        public static let toolMessage = Color(hex: 0x888888)
        public static let hudGreen = Color(hex: 0xD0D0D0)
        public static let hudYellow = Color(hex: 0x999999)
        public static let hudOrange = Color(hex: 0x777777)
        public static let hudRed = Color(hex: 0x555555)
    }

    // MARK: - Spacing (4px base grid)

    public enum Spacing {
    public static let xs: CGFloat = 4
    public static let sm: CGFloat = 8
    public static let md: CGFloat = 12
    public static let base: CGFloat = 16
    public static let lg: CGFloat = 24
    public static let xl: CGFloat = 32
    public static let _2xl: CGFloat = 48
    public static let _3xl: CGFloat = 64
    }

    // MARK: - Radius

    public enum Radius {
    public static let none: CGFloat = 0
    public static let sm: CGFloat = 4
    public static let md: CGFloat = 8
    public static let lg: CGFloat = 12
    public static let xl: CGFloat = 16
    public static let pill: CGFloat = 999
    public static let round: CGFloat = 9999
    }

    // MARK: - Typography

    public enum Typography {
    public static let size_xs: CGFloat = 12
    public static let size_sm: CGFloat = 14
    public static let size_base: CGFloat = 16
    public static let size_md: CGFloat = 17
    public static let size_lg: CGFloat = 20
    public static let size_xl: CGFloat = 24
    public static let size_2xl: CGFloat = 28
    public static let size_3xl: CGFloat = 34
    public static let weight_regular: Int = 400
    public static let weight_medium: Int = 500
    public static let weight_semibold: Int = 600
    public static let weight_bold: Int = 700
    }

    // MARK: - Motion (seconds)

    public enum Duration {
    public static let instant: TimeInterval = 0.080
    public static let fast: TimeInterval = 0.150
    public static let base: TimeInterval = 0.240
    public static let slow: TimeInterval = 0.400
    public static let deliberate: TimeInterval = 0.600
    }
}

// Fallback Color(hex:) in case the host target doesn't already define it.
#if !WOTANN_HAS_COLOR_HEX
private extension Color {
    init(hex: UInt, alpha: Double = 1.0) {
        let r = Double((hex >> 16) & 0xFF) / 255.0
        let g = Double((hex >> 8) & 0xFF) / 255.0
        let b = Double(hex & 0xFF) / 255.0
        self.init(.sRGB, red: r, green: g, blue: b, opacity: alpha)
    }
}
#endif
