/**
 * Shell init snippets — emit OSC 133 sequences so WOTANN can render
 * Warp-style blocks for external shells (zsh, bash, fish).
 *
 * Each generator returns:
 *   - `script`: the shell code that installs prompt / preexec / precmd hooks.
 *   - `sourceLine`: the line the user adds to their rc file to load it.
 *   - `rcPath`: the canonical rc file for the shell (for helpful hints).
 *
 * Pure functions; no file I/O, no process spawning. The CLI layer is
 * responsible for writing to disk.
 */

export type SupportedShell = "zsh" | "bash" | "fish";

export interface ShellInitResult {
  /** Shell name. */
  readonly shell: SupportedShell;
  /** The init script contents to write (e.g. ~/.wotann/shell/wotann.zsh). */
  readonly script: string;
  /** One-line loader the user adds to their rc file. */
  readonly sourceLine: string;
  /** Filename the init script should be saved as. */
  readonly filename: string;
  /** Canonical rc path for this shell (informational). */
  readonly rcPath: string;
}

const OSC = "\\033]133;";
const BEL = "\\007";

/** ── ZSH ─────────────────────────────────────────────────── */

function zshScript(): string {
  // zsh provides precmd (runs before each prompt) and preexec (runs just
  // before a command executes). We use them to bracket the four OSC 133
  // markers. The exit code is captured from $? in the D marker.
  return `# WOTANN OSC 133 shell integration — zsh
# Generated by 'wotann init --shell zsh'. Do not edit by hand; re-run the
# command to regenerate. Compatible with Warp, kitty, wezterm, VS Code, etc.

__wotann_osc133_last_status=0

# A — Prompt begin. Emitted at the start of every prompt render.
# C — Output begin. Emitted after preexec so any tool output is scoped.
# D — Output end + exit code. Emitted at precmd before the next A.

__wotann_osc133_precmd() {
  __wotann_osc133_last_status=$?
  # D;<exit-code>
  printf '${OSC}D;%s${BEL}' "$__wotann_osc133_last_status"
  # A — new prompt starting.
  printf '${OSC}A${BEL}'
}

__wotann_osc133_preexec() {
  # B — command begin. The user just pressed enter.
  printf '${OSC}B${BEL}'
  # C — output begin. Shell is about to run the command; its output belongs
  #     to this block until the next D.
  printf '${OSC}C${BEL}'
}

# Register hooks without clobbering existing ones.
autoload -Uz add-zsh-hook
add-zsh-hook precmd __wotann_osc133_precmd
add-zsh-hook preexec __wotann_osc133_preexec
`;
}

/** ── BASH ────────────────────────────────────────────────── */

function bashScript(): string {
  // Bash doesn't have precmd/preexec natively; we emulate via PROMPT_COMMAND
  // (runs before each prompt) and a DEBUG trap (runs before every command).
  // Guard the DEBUG trap so it only fires once per command, not per function.
  return `# WOTANN OSC 133 shell integration — bash
# Generated by 'wotann init --shell bash'. Do not edit by hand; re-run the
# command to regenerate. Requires bash 4.0+.

__wotann_osc133_last_status=0
__wotann_osc133_command_started=0

__wotann_osc133_debug_trap() {
  # Skip if we're already inside the preexec (i.e. a function calling itself)
  # and skip PROMPT_COMMAND itself (which runs as part of prompt setup).
  if [ "\${BASH_COMMAND}" = "\${PROMPT_COMMAND:-}" ]; then
    return 0
  fi
  if [ "$__wotann_osc133_command_started" = "1" ]; then
    return 0
  fi
  __wotann_osc133_command_started=1
  # B — command begin.
  printf '${OSC}B${BEL}'
  # C — output begin.
  printf '${OSC}C${BEL}'
}

__wotann_osc133_prompt() {
  __wotann_osc133_last_status=$?
  # D — output end with exit code.
  printf '${OSC}D;%s${BEL}' "$__wotann_osc133_last_status"
  # Reset the per-command latch so the next DEBUG trap fires.
  __wotann_osc133_command_started=0
  # A — new prompt begin.
  printf '${OSC}A${BEL}'
}

# Install the DEBUG trap for preexec and the PROMPT_COMMAND for precmd.
trap '__wotann_osc133_debug_trap' DEBUG
if [[ "\${PROMPT_COMMAND:-}" != *__wotann_osc133_prompt* ]]; then
  PROMPT_COMMAND="__wotann_osc133_prompt;\${PROMPT_COMMAND:-}"
fi
`;
}

/** ── FISH ────────────────────────────────────────────────── */

function fishScript(): string {
  // fish has first-class events (fish_prompt, fish_preexec, fish_postexec).
  return `# WOTANN OSC 133 shell integration — fish
# Generated by 'wotann init --shell fish'. Do not edit by hand; re-run the
# command to regenerate. Compatible with fish 3.0+.

function __wotann_osc133_prompt --on-event fish_prompt
    # A — prompt begin.
    printf '\\e]133;A\\a'
end

function __wotann_osc133_preexec --on-event fish_preexec
    # B — command begin.
    printf '\\e]133;B\\a'
    # C — output begin.
    printf '\\e]133;C\\a'
end

function __wotann_osc133_postexec --on-event fish_postexec
    # D — output end with exit code ($status in fish).
    printf '\\e]133;D;%s\\a' $status
end
`;
}

/** Build an init result for the requested shell. */
export function buildShellInit(shell: SupportedShell): ShellInitResult {
  switch (shell) {
    case "zsh":
      return {
        shell,
        script: zshScript(),
        filename: "wotann.zsh",
        sourceLine: "source ~/.wotann/shell/wotann.zsh",
        rcPath: "~/.zshrc",
      };
    case "bash":
      return {
        shell,
        script: bashScript(),
        filename: "wotann.bash",
        sourceLine: "source ~/.wotann/shell/wotann.bash",
        rcPath: "~/.bashrc",
      };
    case "fish":
      return {
        shell,
        script: fishScript(),
        filename: "wotann.fish",
        sourceLine: "source ~/.wotann/shell/wotann.fish",
        // fish convention is conf.d autoload, but source is simpler for users.
        rcPath: "~/.config/fish/config.fish",
      };
    default:
      return assertNever(shell);
  }
}

/** List of shells we support. */
export const SUPPORTED_SHELLS: readonly SupportedShell[] = ["zsh", "bash", "fish"];

/** Type guard for SupportedShell. */
export function isSupportedShell(value: string): value is SupportedShell {
  return (SUPPORTED_SHELLS as readonly string[]).includes(value);
}

function assertNever(value: never): never {
  throw new Error(`buildShellInit: unsupported shell ${String(value)}`);
}
