/* AUTO-GENERATED by src/design/token-emitters/desktop.ts. DO NOT EDIT.
 * Source: src/design/tokens.ts
 * Regenerate: node scripts/generate-tokens.mjs
 */

export const WOTANN_TOKENS = {
  palettes: {
  "dark": {
    "background": "#08080c",
    "surface": "#131318",
    "text": "#e6e6eb",
    "muted": "#8b8b96",
    "border": "#2a2a33",
    "accent": "#06b6d4",
    "accentMuted": "#0891b2",
    "info": "#60a5fa",
    "success": "#34d399",
    "warning": "#fbbf24",
    "error": "#f87171",
    "userMessage": "#60a5fa",
    "assistantMessage": "#34d399",
    "systemMessage": "#fbbf24",
    "toolMessage": "#06b6d4",
    "hudGreen": "#34d399",
    "hudYellow": "#fbbf24",
    "hudOrange": "#f97316",
    "hudRed": "#f87171"
  },
  "light": {
    "background": "#fafafa",
    "surface": "#f0f0f3",
    "text": "#1e1e24",
    "muted": "#6b6b75",
    "border": "#d4d4dc",
    "accent": "#0891b2",
    "accentMuted": "#0e7490",
    "info": "#2563eb",
    "success": "#059669",
    "warning": "#d97706",
    "error": "#dc2626",
    "userMessage": "#2563eb",
    "assistantMessage": "#059669",
    "systemMessage": "#d97706",
    "toolMessage": "#0891b2",
    "hudGreen": "#059669",
    "hudYellow": "#d97706",
    "hudOrange": "#ea580c",
    "hudRed": "#dc2626"
  },
  "high-contrast": {
    "background": "#000000",
    "surface": "#0a0a0a",
    "text": "#ffffff",
    "muted": "#cccccc",
    "border": "#ffffff",
    "accent": "#00ffff",
    "accentMuted": "#00cccc",
    "info": "#00ffff",
    "success": "#00ff00",
    "warning": "#ffff00",
    "error": "#ff0000",
    "userMessage": "#00ffff",
    "assistantMessage": "#00ff00",
    "systemMessage": "#ffff00",
    "toolMessage": "#ffffff",
    "hudGreen": "#00ff00",
    "hudYellow": "#ffff00",
    "hudOrange": "#ff8000",
    "hudRed": "#ff0000"
  },
  "sepia": {
    "background": "#1a1410",
    "surface": "#241b14",
    "text": "#ebd5b3",
    "muted": "#9c8972",
    "border": "#3d2f1f",
    "accent": "#d4a853",
    "accentMuted": "#a88540",
    "info": "#c8a876",
    "success": "#8cb368",
    "warning": "#e8a857",
    "error": "#c87a5e",
    "userMessage": "#c8a876",
    "assistantMessage": "#d4a853",
    "systemMessage": "#e8a857",
    "toolMessage": "#b89468",
    "hudGreen": "#8cb368",
    "hudYellow": "#e8a857",
    "hudOrange": "#d17d3d",
    "hudRed": "#c87a5e"
  },
  "monochrome": {
    "background": "#000000",
    "surface": "#111111",
    "text": "#e0e0e0",
    "muted": "#808080",
    "border": "#333333",
    "accent": "#ffffff",
    "accentMuted": "#cccccc",
    "info": "#bdbdbd",
    "success": "#d0d0d0",
    "warning": "#999999",
    "error": "#666666",
    "userMessage": "#e0e0e0",
    "assistantMessage": "#ffffff",
    "systemMessage": "#aaaaaa",
    "toolMessage": "#888888",
    "hudGreen": "#d0d0d0",
    "hudYellow": "#999999",
    "hudOrange": "#777777",
    "hudRed": "#555555"
  }
  },
  typography: {
    "family": {
      "sans": "\"Inter Variable\", \"SF Pro Text\", system-ui, sans-serif",
      "mono": "\"JetBrains Mono Variable\", \"SF Mono\", ui-monospace, monospace",
      "display": "\"Geist Sans\", \"Inter Variable\", system-ui, sans-serif"
    },
    "size": {
      "xs": 12,
      "sm": 14,
      "base": 16,
      "md": 17,
      "lg": 20,
      "xl": 24,
      "2xl": 28,
      "3xl": 34
    },
    "weight": {
      "regular": 400,
      "medium": 500,
      "semibold": 600,
      "bold": 700
    },
    "lineHeight": {
      "tight": 1.2,
      "normal": 1.5,
      "relaxed": 1.75
    },
    "letterSpacing": {
      "tight": -0.5,
      "normal": 0,
      "wide": 0.5
    }
  },
  spacing: {
    "xs": 4,
    "sm": 8,
    "md": 12,
    "base": 16,
    "lg": 24,
    "xl": 32,
    "2xl": 48,
    "3xl": 64
  },
  radius: {
    "none": 0,
    "sm": 4,
    "md": 8,
    "lg": 12,
    "xl": 16,
    "pill": 999,
    "round": 9999
  },
  shadow: {
    none: "none",
    sm: "0px 1px 2px 0px rgba(0, 0, 0, 0.35)",
    md: "0px 4px 12px 0px rgba(0, 0, 0, 0.45)",
    lg: "0px 12px 32px 0px rgba(0, 0, 0, 0.55)",
    xl: "0px 24px 48px -8px rgba(0, 0, 0, 0.6), 0px 8px 16px -4px rgba(0, 0, 0, 0.35)"
  },
  motion: {
    duration: {
      "instant": 80,
      "fast": 150,
      "base": 240,
      "slow": 400,
      "deliberate": 600
    },
    easing: {
    standard: "cubic-bezier(0.4, 0.14, 0.3, 1)",
    productive: "cubic-bezier(0.4, 0, 0.2, 1)",
    expoOut: "cubic-bezier(0.16, 1, 0.3, 1)",
    pop: "cubic-bezier(0.34, 1.56, 0.64, 1)"
    },
  },
} as const;

export type WotannPaletteName = keyof typeof WOTANN_TOKENS.palettes;
export type WotannColorToken = keyof (typeof WOTANN_TOKENS.palettes)[WotannPaletteName];

/** CSS custom-property name for a color token, e.g. "accent" -> "--wotann-color-accent". */
export function cssVarForColor(token: WotannColorToken): string {
  return `--wotann-color-${token.replace(/([a-z])([A-Z])/g, "$1-$2").toLowerCase()}`;
}

/** Convenience: `var(--wotann-color-accent)` string ready to drop into inline styles. */
export function color(token: WotannColorToken): string {
  return `var(${cssVarForColor(token)})`;
}

/** Convenience: `var(--wotann-space-base)` etc. */
export function space(token: keyof typeof WOTANN_TOKENS.spacing): string {
  return `var(--wotann-space-${token})`;
}

/** Convenience: `var(--wotann-radius-md)` etc. */
export function radius(token: keyof typeof WOTANN_TOKENS.radius): string {
  return `var(--wotann-radius-${token})`;
}

/** Convenience: `var(--wotann-shadow-md)` etc. */
export function shadow(token: "none" | "sm" | "md" | "lg" | "xl"): string {
  return `var(--wotann-shadow-${token})`;
}
