/**
 * CanvasToCode — export a Canvas to a React/JSX component tree.
 *
 * Pairs with `extractor.ts` (which goes the *opposite* direction — codebase
 * → design system). Given a Canvas, we emit a single React component whose
 * children mirror the Canvas elements, with connections surfaced as inline
 * aria hints + data attributes so downstream code can wire event handlers.
 *
 * Design-system integration
 * -------------------------
 * When a Canvas carries a `tokens: DesignSystemRef` and the caller threads
 * in an extracted `DesignSystem`, we resolve color/spacing/typography
 * references in element `props` to CSS custom properties. Unresolved refs
 * stay as literal strings (honest — we don't fabricate values just to
 * close a gap).
 *
 * Honesty bars
 * ------------
 * - Empty canvas → empty return component (no `null` body, no guess).
 * - Unknown element type → `UnknownElement` component with a warning
 *   comment. Never silently dropped.
 * - Deterministic: same (canvas, tokens) produces byte-identical output
 *   — sort elements by a stable key so git diffs are readable.
 * - String identifiers are sanitized (alphanumeric + `_`) when used as
 *   JSX component names; the original id is always emitted as the
 *   `data-canvas-id` attribute so the mapping survives round-trips.
 */

import type { Canvas, CanvasEdge, CanvasElement, CanvasElementProps } from "./canvas.js";
import type { DesignSystem } from "./extractor.js";

// ── Public types ─────────────────────────────────────────────────────────

export interface CanvasToCodeOptions {
  /**
   * Optional extracted `DesignSystem` to resolve token references in
   * element props. If omitted, props are emitted literally.
   */
  readonly tokens?: DesignSystem;
  /**
   * Emit format. Default `tsx`. JSX works for plain React projects;
   * TSX emits the same plus a `Props` type declaration.
   */
  readonly format?: "jsx" | "tsx";
  /** Component name. Sanitized. Default: PascalCase of Canvas.name. */
  readonly componentName?: string;
  /**
   * Indent width. Default 2. Accepts 2 or 4.
   */
  readonly indent?: 2 | 4;
}

export interface CanvasExportResult {
  readonly code: string;
  readonly componentName: string;
  readonly elementCount: number;
  readonly edgeCount: number;
  readonly warnings: readonly string[];
}

// ── Entry point ──────────────────────────────────────────────────────────

export function canvasToCode(canvas: Canvas, opts: CanvasToCodeOptions = {}): CanvasExportResult {
  const indent = opts.indent ?? 2;
  const format = opts.format ?? "tsx";
  const componentName = sanitizeComponentName(opts.componentName ?? canvas.name);
  const warnings: string[] = [];

  const elements = [...canvas.elements].sort((a, b) => a.id.localeCompare(b.id));
  const edgeMap = buildEdgeMap(canvas.connections);

  const lines: string[] = [];
  const indentStr = " ".repeat(indent);

  if (format === "tsx") {
    lines.push("// Auto-generated by wotann design canvas-to-code.");
    lines.push(`// Source canvas: ${canvas.id} (v${canvas.version})`);
    lines.push(`// Elements: ${canvas.elements.length}  Connections: ${canvas.connections.length}`);
    if (canvas.tokens) {
      lines.push(`// Tokens ref: ${canvas.tokens.id}`);
    }
    lines.push("");
    lines.push(`export interface ${componentName}Props {`);
    lines.push(`${indentStr}readonly canvasId?: string;`);
    lines.push("}");
    lines.push("");
    lines.push(
      `export function ${componentName}(props: ${componentName}Props = {}): JSX.Element {`,
    );
  } else {
    lines.push("// Auto-generated by wotann design canvas-to-code.");
    lines.push(`// Source canvas: ${canvas.id} (v${canvas.version})`);
    lines.push("");
    lines.push(`export function ${componentName}(props) {`);
  }

  lines.push(`${indentStr}return (`);
  lines.push(
    `${indentStr}${indentStr}<section data-canvas-id=${JSON.stringify(canvas.id)} data-canvas-version={${canvas.version}}>`,
  );

  if (elements.length === 0) {
    lines.push(`${indentStr}${indentStr}${indentStr}{/* Canvas has no elements yet. */}`);
  }

  for (const el of elements) {
    lines.push(
      ...renderElement(el, edgeMap.get(el.id) ?? [], opts.tokens, indentStr.repeat(3), warnings),
    );
  }

  lines.push(`${indentStr}${indentStr}</section>`);
  lines.push(`${indentStr});`);
  lines.push("}");

  return {
    code: lines.join("\n") + "\n",
    componentName,
    elementCount: elements.length,
    edgeCount: canvas.connections.length,
    warnings,
  };
}

// ── Rendering ────────────────────────────────────────────────────────────

function renderElement(
  el: CanvasElement,
  outgoing: readonly CanvasEdge[],
  tokens: DesignSystem | undefined,
  indent: string,
  warnings: string[],
): string[] {
  const lines: string[] = [];
  const tag = tagForType(el.type);
  if (tag === null) {
    warnings.push(`unknown element type "${el.type}" for element ${el.id}`);
    lines.push(`${indent}{/* unknown element type: ${el.type} */}`);
    lines.push(`${indent}<div data-canvas-id=${JSON.stringify(el.id)} />`);
    return lines;
  }

  const attrs = buildAttrs(el, outgoing, tokens);
  if (attrs.length === 0) {
    lines.push(`${indent}<${tag} />`);
    return lines;
  }

  const style = buildStyle(el, tokens);
  const attrText = attrs
    .map(([k, v]) => (typeof v === "string" ? `${k}=${JSON.stringify(v)}` : `${k}={${v}}`))
    .join(" ");
  const styleText = style ? ` style={${style}}` : "";

  if (el.type === "text" || el.type === "annotation") {
    const body = String(el.props["text"] ?? el.props["content"] ?? "");
    const safeBody = body
      .replace(/</g, "&lt;")
      .replace(/>/g, "&gt;")
      .replace(/\{/g, "&#123;")
      .replace(/\}/g, "&#125;");
    lines.push(`${indent}<${tag} ${attrText}${styleText}>${safeBody}</${tag}>`);
  } else {
    lines.push(`${indent}<${tag} ${attrText}${styleText} />`);
  }
  return lines;
}

function tagForType(type: string): string | null {
  switch (type) {
    case "component":
      return "div";
    case "section":
      return "section";
    case "text":
      return "p";
    case "annotation":
      return "aside";
    default:
      return null;
  }
}

function buildAttrs(
  el: CanvasElement,
  outgoing: readonly CanvasEdge[],
  _tokens: DesignSystem | undefined,
): Array<[string, string | number]> {
  const out: Array<[string, string | number]> = [];
  out.push(["data-canvas-id", el.id]);
  out.push(["data-canvas-type", el.type]);
  if (el.props["name"] !== undefined) {
    out.push(["data-name", String(el.props["name"])]);
  }
  if (outgoing.length > 0) {
    const labels = outgoing.map((e) => `${e.kind}:${e.to}`).join(",");
    out.push(["data-canvas-edges", labels]);
  }
  // Propagate untreated string/number props as data-* attrs for loss-free
  // round-trip. Booleans become "true"/"false" literal values.
  for (const [key, value] of Object.entries(el.props)) {
    if (key === "name" || key === "text" || key === "content") continue;
    if (typeof value === "boolean") {
      out.push([`data-${kebab(key)}`, value ? "true" : "false"]);
    } else {
      out.push([`data-${kebab(key)}`, value]);
    }
  }
  return out;
}

function buildStyle(el: CanvasElement, tokens: DesignSystem | undefined): string | null {
  const parts: string[] = [];
  parts.push(`position: "absolute"`);
  parts.push(`left: ${el.position.x}`);
  parts.push(`top: ${el.position.y}`);
  parts.push(`width: ${el.position.width}`);
  parts.push(`height: ${el.position.height}`);

  // Token resolution — if the canvas props reference a token id that the
  // DesignSystem knows about, emit a CSS variable reference. We keep this
  // conservative: only `color` / `background` / `fontFamily` / `fontSize`
  // strings that match a known token value trigger the lookup.
  if (tokens) {
    const color = maybeResolveColor(el.props["color"], tokens);
    if (color !== null) parts.push(`color: ${JSON.stringify(color)}`);
    const bg = maybeResolveColor(el.props["background"], tokens);
    if (bg !== null) parts.push(`background: ${JSON.stringify(bg)}`);
    const fontFamily = maybeResolveFontFamily(el.props["fontFamily"], tokens);
    if (fontFamily !== null) parts.push(`fontFamily: ${JSON.stringify(fontFamily)}`);
    const fontSize = maybeResolveFontSize(el.props["fontSize"], tokens);
    if (fontSize !== null) parts.push(`fontSize: ${JSON.stringify(fontSize)}`);
  }

  return `{ ${parts.join(", ")} }`;
}

// ── Token resolution helpers (honest — only lookups, no inventions) ──────

function maybeResolveColor(
  propValue: CanvasElementProps[keyof CanvasElementProps] | undefined,
  tokens: DesignSystem,
): string | null {
  if (typeof propValue !== "string" || propValue === "") return null;
  for (const pal of tokens.palettes) {
    for (const c of pal.colors) {
      if (c.value.toLowerCase() === propValue.toLowerCase()) {
        return c.value;
      }
    }
  }
  return null;
}

function maybeResolveFontFamily(
  propValue: CanvasElementProps[keyof CanvasElementProps] | undefined,
  tokens: DesignSystem,
): string | null {
  if (typeof propValue !== "string" || propValue === "") return null;
  for (const fam of tokens.typography.fontFamilies) {
    if (fam.value === propValue) return fam.value;
  }
  return null;
}

function maybeResolveFontSize(
  propValue: CanvasElementProps[keyof CanvasElementProps] | undefined,
  tokens: DesignSystem,
): string | null {
  if (typeof propValue !== "string" || propValue === "") return null;
  for (const sz of tokens.typography.fontSizes) {
    if (sz.raw === propValue) return sz.raw;
  }
  return null;
}

// ── Utils ────────────────────────────────────────────────────────────────

function buildEdgeMap(edges: readonly CanvasEdge[]): Map<string, CanvasEdge[]> {
  const map = new Map<string, CanvasEdge[]>();
  for (const e of edges) {
    const bucket = map.get(e.from);
    if (bucket) bucket.push(e);
    else map.set(e.from, [e]);
  }
  return map;
}

function kebab(s: string): string {
  return s
    .replace(/([a-z0-9])([A-Z])/g, "$1-$2")
    .replace(/[_\s]+/g, "-")
    .toLowerCase();
}

function sanitizeComponentName(raw: string): string {
  const cleaned = raw
    .replace(/[^A-Za-z0-9]+/g, " ")
    .trim()
    .split(/\s+/)
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join("");
  if (cleaned === "" || /^\d/.test(cleaned)) {
    return `Canvas${cleaned}`;
  }
  return cleaned;
}
