import UIKit
import Runestone

// MARK: - EditorThemes
//
// Light and dark theme tokens for the Runestone editor, plus a syntax-color
// mapping that drives highlight queries generated by the TreeSitter language
// packs.
//
// WHY INLINE (not delegated to WTheme):
// The T13 iOS background agent is sandboxed from `WOTANN/DesignSystem/`
// (owned by the T7 agent). Rather than risk merge conflicts by reaching into
// `WTheme.Colors` we define editor-scoped tokens here. If the T7 agent ever
// exposes matching `WTheme.Editor.*` tokens upstream, these values can be
// trivially re-pointed without touching call sites in `RunestoneEditorView`
// or `EditorService`.
//
// Color choices intentionally mirror the Obsidian Precision palette used by
// the rest of the app (OLED-black surface, Apple-blue accent, SF Pro Mono).
// Both themes were eye-balled against XCode's "Default Dark" and "Default"
// so the editor feels native on day one.

// MARK: - EditorColorKind
//
// Stable enum of every syntax scope the editor paints. The raw value matches
// the TreeSitter highlight name so the generated themes can be wired into
// Runestone's `HighlightName` table with zero translation work.

enum EditorColorKind: String, CaseIterable {
    case keyword         = "keyword"
    case identifier      = "variable"
    case type            = "type"
    case string          = "string"
    case number          = "number"
    case comment         = "comment"
    case functionCall    = "function"
    case operatorSymbol  = "operator"
    case punctuation     = "punctuation"
    case constant        = "constant"
    case attribute       = "attribute"
    case property        = "property"
    case tag             = "tag"
    case plain           = "plain"
}

// MARK: - EditorThemeMode

/// Two canonical modes the editor supports. System mode follows UITraitCollection.
enum EditorThemeMode: String, CaseIterable, Identifiable {
    case light
    case dark
    case system

    var id: String { rawValue }

    var displayName: String {
        switch self {
        case .light:  return "Light"
        case .dark:   return "Dark"
        case .system: return "System"
        }
    }
}

// MARK: - EditorTheme (immutable value type)
//
// A pure value bag — every field is a color/font/size. No behaviour. This
// keeps the theme itself easily snapshot-testable and safe to cache.

struct EditorTheme: Equatable {
    let mode: EditorThemeMode
    let backgroundColor: UIColor
    let textColor: UIColor
    let gutterBackgroundColor: UIColor
    let gutterTextColor: UIColor
    let selectionBackgroundColor: UIColor
    let selectedLineBackgroundColor: UIColor
    let invisibleCharactersColor: UIColor
    let cursorColor: UIColor
    let markedTextBackgroundColor: UIColor
    let syntaxColors: [EditorColorKind: UIColor]
    let font: UIFont
    let fontSize: CGFloat

    // MARK: - Runestone bridge
    //
    // Returns a lightweight struct that conforms to `Runestone.Theme`. We
    // build it lazily so consumers that only want the tokens (e.g. unit
    // tests) don't have to link UIKit text rendering.

    func runestoneTheme() -> RunestoneTheme {
        RunestoneTheme(theme: self)
    }
}

// MARK: - EditorThemes (factories)

enum EditorThemes {

    // Apple-blue accent shared by both themes — matches WTheme.Colors.primary
    // so the editor cursor feels at home with the rest of the iOS app.
    static let accent = UIColor(red: 0x0A / 255.0, green: 0x84 / 255.0, blue: 0xFF / 255.0, alpha: 1.0)

    // MARK: Dark (default)

    static let dark: EditorTheme = EditorTheme(
        mode: .dark,
        backgroundColor:            UIColor.black,
        textColor:                  UIColor.white,
        gutterBackgroundColor:      UIColor(white: 0.07, alpha: 1.0),
        gutterTextColor:            UIColor(white: 0.50, alpha: 1.0),
        selectionBackgroundColor:   accent.withAlphaComponent(0.30),
        selectedLineBackgroundColor: UIColor(white: 0.10, alpha: 1.0),
        invisibleCharactersColor:   UIColor(white: 0.25, alpha: 1.0),
        cursorColor:                accent,
        markedTextBackgroundColor:  accent.withAlphaComponent(0.25),
        syntaxColors: [
            .keyword:        UIColor(red: 1.00, green: 0.47, blue: 0.67, alpha: 1.0),
            .identifier:     UIColor(red: 0.92, green: 0.92, blue: 0.92, alpha: 1.0),
            .type:           UIColor(red: 0.55, green: 0.80, blue: 1.00, alpha: 1.0),
            .string:         UIColor(red: 0.98, green: 0.70, blue: 0.55, alpha: 1.0),
            .number:         UIColor(red: 0.90, green: 0.72, blue: 1.00, alpha: 1.0),
            .comment:        UIColor(red: 0.45, green: 0.52, blue: 0.58, alpha: 1.0),
            .functionCall:   UIColor(red: 0.60, green: 0.85, blue: 0.95, alpha: 1.0),
            .operatorSymbol: UIColor(red: 0.80, green: 0.80, blue: 0.85, alpha: 1.0),
            .punctuation:    UIColor(red: 0.70, green: 0.70, blue: 0.75, alpha: 1.0),
            .constant:       UIColor(red: 1.00, green: 0.80, blue: 0.55, alpha: 1.0),
            .attribute:      UIColor(red: 0.85, green: 0.75, blue: 1.00, alpha: 1.0),
            .property:       UIColor(red: 0.70, green: 0.90, blue: 0.80, alpha: 1.0),
            .tag:            UIColor(red: 0.98, green: 0.60, blue: 0.60, alpha: 1.0),
            .plain:          UIColor.white,
        ],
        font:     UIFont.monospacedSystemFont(ofSize: 14, weight: .regular),
        fontSize: 14
    )

    // MARK: Light

    static let light: EditorTheme = EditorTheme(
        mode: .light,
        backgroundColor:            UIColor.white,
        textColor:                  UIColor(white: 0.10, alpha: 1.0),
        gutterBackgroundColor:      UIColor(white: 0.97, alpha: 1.0),
        gutterTextColor:            UIColor(white: 0.55, alpha: 1.0),
        selectionBackgroundColor:   accent.withAlphaComponent(0.22),
        selectedLineBackgroundColor: UIColor(white: 0.95, alpha: 1.0),
        invisibleCharactersColor:   UIColor(white: 0.80, alpha: 1.0),
        cursorColor:                accent,
        markedTextBackgroundColor:  accent.withAlphaComponent(0.20),
        syntaxColors: [
            .keyword:        UIColor(red: 0.70, green: 0.10, blue: 0.40, alpha: 1.0),
            .identifier:     UIColor(red: 0.10, green: 0.10, blue: 0.12, alpha: 1.0),
            .type:           UIColor(red: 0.15, green: 0.35, blue: 0.75, alpha: 1.0),
            .string:         UIColor(red: 0.65, green: 0.20, blue: 0.10, alpha: 1.0),
            .number:         UIColor(red: 0.55, green: 0.15, blue: 0.70, alpha: 1.0),
            .comment:        UIColor(red: 0.35, green: 0.45, blue: 0.35, alpha: 1.0),
            .functionCall:   UIColor(red: 0.20, green: 0.40, blue: 0.70, alpha: 1.0),
            .operatorSymbol: UIColor(red: 0.20, green: 0.20, blue: 0.25, alpha: 1.0),
            .punctuation:    UIColor(red: 0.30, green: 0.30, blue: 0.35, alpha: 1.0),
            .constant:       UIColor(red: 0.70, green: 0.35, blue: 0.05, alpha: 1.0),
            .attribute:      UIColor(red: 0.40, green: 0.25, blue: 0.70, alpha: 1.0),
            .property:       UIColor(red: 0.15, green: 0.50, blue: 0.30, alpha: 1.0),
            .tag:            UIColor(red: 0.70, green: 0.10, blue: 0.15, alpha: 1.0),
            .plain:          UIColor(white: 0.10, alpha: 1.0),
        ],
        font:     UIFont.monospacedSystemFont(ofSize: 14, weight: .regular),
        fontSize: 14
    )

    // MARK: Resolver

    /// Resolve a theme for the given mode. `.system` falls back to the
    /// supplied `traitCollection` so callers can honour live appearance
    /// changes without rebuilding their theme pipeline.
    static func resolve(_ mode: EditorThemeMode, traits: UITraitCollection = .current) -> EditorTheme {
        switch mode {
        case .light:  return light
        case .dark:   return dark
        case .system: return traits.userInterfaceStyle == .light ? light : dark
        }
    }
}

// MARK: - RunestoneTheme (Runestone.Theme bridge)
//
// Thin adapter that maps our `EditorTheme` onto whatever the installed
// Runestone SPM version exposes. The property names below are stable across
// the 0.5.x series. If the upstream API shifts we localise the change here.

struct RunestoneTheme: Runestone.Theme {
    let theme: EditorTheme

    var backgroundColor: UIColor            { theme.backgroundColor }
    var textColor: UIColor                  { theme.textColor }
    var gutterBackgroundColor: UIColor      { theme.gutterBackgroundColor }
    var gutterHairlineColor: UIColor        { theme.gutterBackgroundColor }
    var lineNumberColor: UIColor            { theme.gutterTextColor }
    var lineNumberFont: UIFont              { theme.font }
    var selectedLineBackgroundColor: UIColor { theme.selectedLineBackgroundColor }
    var selectedLinesLineNumberColor: UIColor { theme.textColor }
    var selectedLinesGutterBackgroundColor: UIColor { theme.selectedLineBackgroundColor }
    var invisibleCharactersColor: UIColor   { theme.invisibleCharactersColor }
    var pageGuideHairlineColor: UIColor     { theme.gutterTextColor.withAlphaComponent(0.20) }
    var pageGuideBackgroundColor: UIColor   { theme.backgroundColor }
    var markedTextBackgroundColor: UIColor  { theme.markedTextBackgroundColor }
    var font: UIFont                        { theme.font }

    // Runestone asks for a (color, bold, italic) triple per highlight name.
    func textColor(for highlightName: String) -> UIColor? {
        let kind = EditorColorKind(rawValue: highlightName) ?? .plain
        return theme.syntaxColors[kind] ?? theme.textColor
    }

    func fontTraits(for highlightName: String) -> FontTraits {
        // Bold keywords/types; italic comments — matches XCode default style.
        switch EditorColorKind(rawValue: highlightName) ?? .plain {
        case .keyword, .type: return [.bold]
        case .comment:        return [.italic]
        default:              return []
        }
    }
}
