/**
 * Desktop token emitter — produces CSS custom properties (one `:root` block
 * per palette, selected via `[data-theme="..."]` attribute) and a TS type
 * module that the desktop-app can import for type-safe token usage.
 */

import {
  type CanonicalPaletteName,
  type WotannTokens,
  COLOR_TOKEN_KEYS,
  formatShadowLayer,
  rgbaString,
} from "../tokens.js";

export interface DesktopEmission {
  readonly css: string;
  readonly typescript: string;
}

/**
 * Convert a camelCase token name to kebab-case for CSS variable naming.
 * Keeps numbers attached (e.g. `"2xl"` → `"2xl"`).
 */
function kebab(name: string): string {
  return name.replace(/([a-z])([A-Z])/g, "$1-$2").toLowerCase();
}

function emitPaletteBlock(
  name: CanonicalPaletteName,
  palette: WotannTokens["palettes"][CanonicalPaletteName],
): string {
  const selector = name === "dark" ? `:root, [data-theme="dark"]` : `[data-theme="${name}"]`;
  const lines: string[] = [];
  for (const key of COLOR_TOKEN_KEYS) {
    lines.push(`  --wotann-color-${kebab(key)}: ${palette[key]};`);
  }
  return `${selector} {\n${lines.join("\n")}\n}`;
}

function emitNonColorRoot(tokens: WotannTokens): string {
  const lines: string[] = [];

  // Typography
  for (const [k, v] of Object.entries(tokens.typography.family)) {
    lines.push(`  --wotann-font-${k}: ${v};`);
  }
  for (const [k, v] of Object.entries(tokens.typography.size)) {
    lines.push(`  --wotann-font-size-${k}: ${v}px;`);
  }
  for (const [k, v] of Object.entries(tokens.typography.weight)) {
    lines.push(`  --wotann-font-weight-${k}: ${v};`);
  }
  for (const [k, v] of Object.entries(tokens.typography.lineHeight)) {
    lines.push(`  --wotann-line-height-${k}: ${v};`);
  }
  for (const [k, v] of Object.entries(tokens.typography.letterSpacing)) {
    lines.push(`  --wotann-letter-spacing-${k}: ${v}px;`);
  }

  // Spacing
  for (const [k, v] of Object.entries(tokens.spacing)) {
    lines.push(`  --wotann-space-${k}: ${v}px;`);
  }

  // Radius
  for (const [k, v] of Object.entries(tokens.radius)) {
    lines.push(`  --wotann-radius-${k}: ${v}px;`);
  }

  // Shadow
  lines.push(`  --wotann-shadow-none: none;`);
  for (const k of ["sm", "md", "lg", "xl"] as const) {
    const layers = tokens.shadow[k];
    if (!layers) continue;
    lines.push(`  --wotann-shadow-${k}: ${layers.map(formatShadowLayer).join(", ")};`);
  }

  // Motion
  for (const [k, v] of Object.entries(tokens.motion.duration)) {
    lines.push(`  --wotann-duration-${k}: ${v}ms;`);
  }
  for (const [k, v] of Object.entries(tokens.motion.easing)) {
    lines.push(`  --wotann-ease-${kebab(k)}: cubic-bezier(${v.join(", ")});`);
  }

  return `:root {\n${lines.join("\n")}\n}`;
}

function emitTypescript(tokens: WotannTokens): string {
  // Helper: serialize a plain-object POJO to TS. No cycles, no undefineds.
  const palettesLines: string[] = [];
  for (const name of Object.keys(tokens.palettes) as CanonicalPaletteName[]) {
    const p = tokens.palettes[name];
    const body = COLOR_TOKEN_KEYS.map((k) => `    "${k}": "${p[k]}"`).join(",\n");
    palettesLines.push(`  "${name}": {\n${body}\n  }`);
  }

  const shadowLines: string[] = [];
  shadowLines.push(`  none: "none"`);
  for (const k of ["sm", "md", "lg", "xl"] as const) {
    const layers = tokens.shadow[k];
    shadowLines.push(`  ${k}: "${layers.map(formatShadowLayer).join(", ")}"`);
  }

  const easingLines: string[] = [];
  for (const [k, v] of Object.entries(tokens.motion.easing)) {
    easingLines.push(`    ${k}: "cubic-bezier(${v.join(", ")})"`);
  }

  return `/* AUTO-GENERATED by src/design/token-emitters/desktop.ts. DO NOT EDIT.
 * Source: src/design/tokens.ts
 * Regenerate: node scripts/generate-tokens.mjs
 */

export const WOTANN_TOKENS = {
  palettes: {
${palettesLines.join(",\n")}
  },
  typography: ${JSON.stringify(tokens.typography, null, 2).replace(/\n/g, "\n  ")},
  spacing: ${JSON.stringify(tokens.spacing, null, 2).replace(/\n/g, "\n  ")},
  radius: ${JSON.stringify(tokens.radius, null, 2).replace(/\n/g, "\n  ")},
  shadow: {
${shadowLines.map((l) => "  " + l).join(",\n")}
  },
  motion: {
    duration: ${JSON.stringify(tokens.motion.duration, null, 2).replace(/\n/g, "\n    ")},
    easing: {
${easingLines.join(",\n")}
    },
  },
} as const;

export type WotannPaletteName = keyof typeof WOTANN_TOKENS.palettes;
export type WotannColorToken = keyof (typeof WOTANN_TOKENS.palettes)[WotannPaletteName];

/** CSS custom-property name for a color token, e.g. "accent" -> "--wotann-color-accent". */
export function cssVarForColor(token: WotannColorToken): string {
  return \`--wotann-color-\${token.replace(/([a-z])([A-Z])/g, "$1-$2").toLowerCase()}\`;
}

/** Convenience: \`var(--wotann-color-accent)\` string ready to drop into inline styles. */
export function color(token: WotannColorToken): string {
  return \`var(\${cssVarForColor(token)})\`;
}

/** Convenience: \`var(--wotann-space-base)\` etc. */
export function space(token: keyof typeof WOTANN_TOKENS.spacing): string {
  return \`var(--wotann-space-\${token})\`;
}

/** Convenience: \`var(--wotann-radius-md)\` etc. */
export function radius(token: keyof typeof WOTANN_TOKENS.radius): string {
  return \`var(--wotann-radius-\${token})\`;
}

/** Convenience: \`var(--wotann-shadow-md)\` etc. */
export function shadow(token: "none" | "sm" | "md" | "lg" | "xl"): string {
  return \`var(--wotann-shadow-\${token})\`;
}
`;
}

export function emitDesktop(tokens: WotannTokens): DesktopEmission {
  const paletteBlocks = (Object.keys(tokens.palettes) as CanonicalPaletteName[]).map((name) =>
    emitPaletteBlock(name, tokens.palettes[name]),
  );
  const css =
    `/* AUTO-GENERATED by src/design/token-emitters/desktop.ts. DO NOT EDIT.\n` +
    ` * Source: src/design/tokens.ts\n` +
    ` * Regenerate: node scripts/generate-tokens.mjs\n` +
    ` */\n\n` +
    emitNonColorRoot(tokens) +
    `\n\n` +
    paletteBlocks.join("\n\n") +
    `\n`;

  return {
    css,
    typescript: emitTypescript(tokens),
  };
}

// Export the rgbaString helper for potential consumers — keeps lint happy.
export { rgbaString };
