/**
 * iOS token emitter — produces a SwiftUI extension file.
 *
 * The existing `ios/WOTANN/DesignSystem/Theme.swift` is the canonical
 * runtime spot, but this emitter generates `WotannTokens.swift` — a
 * regenerable mirror of the unified token graph. That way a designer
 * can tweak `src/design/tokens.ts` and the iOS side picks up the new
 * values after `node scripts/generate-tokens.mjs` runs.
 */

import { type CanonicalPaletteName, type WotannTokens, COLOR_TOKEN_KEYS } from "../tokens.js";

export interface IosEmission {
  readonly swift: string;
}

/**
 * Convert "#abc" or "#aabbcc" into a `0xAABBCC` literal for Swift's
 * `UInt` constructor from Color(hex:).
 */
function hexToSwiftLiteral(hex: string): string {
  let h = hex.trim().replace(/^#/, "");
  if (h.length === 3) {
    h = h
      .split("")
      .map((c) => c + c)
      .join("");
  }
  return `0x${h.toUpperCase()}`;
}

function emitColors(tokens: WotannTokens): string {
  const paletteBlocks: string[] = [];
  for (const name of Object.keys(tokens.palettes) as CanonicalPaletteName[]) {
    const p = tokens.palettes[name];
    const structName = name.replace(/[-_](\w)/g, (_, c: string) => c.toUpperCase());
    const body = COLOR_TOKEN_KEYS.map(
      (k) => `        public static let ${k} = Color(hex: ${hexToSwiftLiteral(p[k])})`,
    ).join("\n");
    paletteBlocks.push(
      `    public enum ${structName.charAt(0).toUpperCase() + structName.slice(1)} {\n${body}\n    }`,
    );
  }
  return paletteBlocks.join("\n\n");
}

function emitSpacing(tokens: WotannTokens): string {
  return Object.entries(tokens.spacing)
    .map(([k, v]) => `    public static let ${k.replace(/^(\d)/, "_$1")}: CGFloat = ${v}`)
    .join("\n");
}

function emitRadius(tokens: WotannTokens): string {
  return Object.entries(tokens.radius)
    .map(([k, v]) => `    public static let ${k}: CGFloat = ${v}`)
    .join("\n");
}

function emitTypography(tokens: WotannTokens): string {
  const sizes = Object.entries(tokens.typography.size)
    .map(
      ([k, v]) => `    public static let size_${k.replace(/[^a-zA-Z0-9]/g, "_")}: CGFloat = ${v}`,
    )
    .join("\n");
  const weights = Object.entries(tokens.typography.weight)
    .map(([k, v]) => `    public static let weight_${k}: Int = ${v}`)
    .join("\n");
  return `${sizes}\n${weights}`;
}

function emitDurations(tokens: WotannTokens): string {
  return Object.entries(tokens.motion.duration)
    .map(([k, v]) => `    public static let ${k}: TimeInterval = ${(v / 1000).toFixed(3)}`)
    .join("\n");
}

export function emitIos(tokens: WotannTokens): IosEmission {
  const swift = `// AUTO-GENERATED by src/design/token-emitters/ios.ts. DO NOT EDIT.
// Source: src/design/tokens.ts
// Regenerate: node scripts/generate-tokens.mjs
//
// Pairs with DesignSystem/Theme.swift — this file provides the raw generated
// token values; Theme.swift composes them into the live runtime API.

import SwiftUI
import Foundation

/// Generated WOTANN design tokens.
public enum WotannTokens {

    // MARK: - Palettes (5 canonical)

${emitColors(tokens)}

    // MARK: - Spacing (4px base grid)

    public enum Spacing {
${emitSpacing(tokens)}
    }

    // MARK: - Radius

    public enum Radius {
${emitRadius(tokens)}
    }

    // MARK: - Typography

    public enum Typography {
${emitTypography(tokens)}
    }

    // MARK: - Motion (seconds)

    public enum Duration {
${emitDurations(tokens)}
    }
}

// Fallback Color(hex:) in case the host target doesn't already define it.
#if !WOTANN_HAS_COLOR_HEX
private extension Color {
    init(hex: UInt, alpha: Double = 1.0) {
        let r = Double((hex >> 16) & 0xFF) / 255.0
        let g = Double((hex >> 8) & 0xFF) / 255.0
        let b = Double(hex & 0xFF) / 255.0
        self.init(.sRGB, red: r, green: g, blue: b, opacity: alpha)
    }
}
#endif
`;

  return { swift };
}
